subdir-ccflags-y += -I$(srctree)/fs/lustre/include
subdir-ccflags-y += -I$(srctree)/fs/lustre/lustre/include

obj-$(CONFIG_LNET) += ksocklnd.o

ksocklnd-y := socklnd.o socklnd_cb.o socklnd_proto.o socklnd_modparams.o socklnd_lib.o
