subdir-ccflags-y += -I$(srctree)/fs/lustre/include
subdir-ccflags-y += -I$(srctree)/fs/lustre/lustre/include

obj-$(CONFIG_LUSTRE_FS) += mdc.o
mdc-y := mdc_request.o mdc_reint.o mdc_lib.o mdc_locks.o lproc_mdc.o
